# Generated by Django 5.0.4 on 2024-05-21 18:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_alter_coursearticle_options_alter_article_courses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursearticle',
            name='order_num',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Порядковый номер занятия'),
        ),
    ]
