# Generated by Django 5.0.4 on 2024-06-19 21:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='year',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(2022), django.core.validators.MaxValueValidator(2040)], verbose_name='Год курса'),
        ),
    ]
