# Generated by Django 5.0.4 on 2024-06-20 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_course_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='name',
            field=models.CharField(max_length=63, verbose_name='Название направления'),
        ),
    ]
